# Generated by Django 4.2.7 on 2023-11-09 11:07

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("email_confirm", models.BooleanField(default=False)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+(?:[0-9] ?){6,14}[0-9]$"
                            )
                        ],
                    ),
                ),
                ("location", django_countries.fields.CountryField(max_length=2)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
