version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
      - celery
      - celery_beat
      - flower

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5432"

  redis:
    image: redis
    restart: always

  celery:
    restart: always
    build:
      context: .
    command: celery -A project worker -l info
    depends_on:
      - redis
    env_file:
      - .env

  celery_beat:
    restart: always
    build: .
    command: celery -A project beat -l info
    depends_on:
      - redis
    env_file:
      - .env
  flower:  # новый сервис для Celery Flower
    restart: always
    build: .
    command: python -m celery -A project flower --port=5556
    ports:
      - "5556:5556"
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  postgres_data:
  static: